export const mockUsers = [
  { user_id: 'USER001', user_name: 'admin', password: 'Admin@2026', ho_ten: 'Admin', role: 'admin', email: 'duc.nt@urbox.vn', active: 'TRUE' },
  { user_id: 'USER002', user_name: 'le.anhtuan', password: 'Tuan@2026', ho_ten: 'Lê Anh Tuấn', role: 'staff', email: 'tuan.la@urbox.vn', active: 'TRUE' },
  { user_id: 'USER003', user_name: 'luong.sontung', password: 'Tung@2026', ho_ten: 'Lương Sơn Tùng', role: 'staff', email: 'tung.ls@urbox.vn', active: 'TRUE' },
  { user_id: 'USER004', user_name: 'nguyen.levan', password: 'Van@2026', ho_ten: 'Nguyễn Lê Văn', role: 'staff', email: 'van.nl@urbox.vn', active: 'TRUE' },
  { user_id: 'USER005', user_name: 'nguyen.hoangtuan', password: 'HoangTuan@2026', ho_ten: 'Nguyễn Hoàng Tuấn', role: 'staff', email: 'tuan.nh@urbox.vn', active: 'TRUE' },
  { user_id: 'USER006', user_name: 'truong.trongtan', password: 'Tan@2026', ho_ten: 'Trương Trọng Tân', role: 'staff', email: 'tan.tt@urbox.vn', active: 'TRUE' }
];

export const mockPOSMData = [
  // --- Lê Anh Tuấn (USER002) ---
  {
    'Week triển khai': 'W1',
    'Ngày chia': '25/03/2026',
    'Brand': 'AEON Mall Tân Phú',
    'Mã cv': 'JOB001',
    'Địa chỉ': '30 Bờ Bao Tân Thắng, Sơn Kỳ, Tân Phú, TP. HCM',
    'Phường': 'Sơn Kỳ',
    'Quận': 'Tân Phú',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Lê Anh Tuấn',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'Tài khoản Portal': 'PORTAL001',
    'latitude': '10.8016',
    'longitude': '106.6167',
    'pic_id': 'USER002'
  },
  {
    'Week triển khai': 'W2',
    'Ngày chia': '28/03/2026',
    'Brand': 'Vincom Plaza Thủ Đức',
    'Mã cv': 'JOB012',
    'Địa chỉ': 'Linh Đông, Thủ Đức, TP. HCM',
    'Phường': 'Linh Đông',
    'Quận': 'Thủ Đức',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Lê Anh Tuấn',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'Tài khoản Portal': 'PORTAL012',
    'latitude': '10.8511',
    'longitude': '106.7577',
    'pic_id': 'USER002'
  },
  {
    'Week triển khai': 'W3',
    'Ngày chia': '01/04/2026',
    'Brand': 'Lotte Mart Bình Dương',
    'Mã cv': 'JOB013',
    'Địa chỉ': 'Đại lộ Bình Dương, Thủ Dầu Một, Bình Dương',
    'Phường': 'Phú Hòa',
    'Quận': 'Thủ Dầu Một',
    'Thành Phố': 'Bình Dương',
    'PIC': 'Lê Anh Tuấn',
    'Status': 'Done',
    'Ngày hoàn thành': '02/04/2026',
    'Tài khoản Portal': 'PORTAL013',
    'latitude': '10.9655',
    'longitude': '106.6460',
    'pic_id': 'USER002'
  },
  // --- Lương Sơn Tùng (USER003) ---
  {
    'Week triển khai': 'W1',
    'Ngày chia': '26/03/2026',
    'Brand': 'Vincom Center Đồng Khởi',
    'Mã cv': 'JOB002',
    'Địa chỉ': '72 Lê Thánh Tôn, Bến Nghé, Quận 1, TP. HCM',
    'Phường': 'Bến Nghé',
    'Quận': 'Quận 1',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Lương Sơn Tùng',
    'Status': 'Done',
    'Ngày hoàn thành': '27/03/2026',
    'Tài khoản Portal': 'PORTAL002',
    'latitude': '10.7779',
    'longitude': '106.7020',
    'pic_id': 'USER003'
  },
  {
    'Week triển khai': 'W3',
    'Ngày chia': '01/04/2026',
    'Brand': 'AEON Mall Hà Đông',
    'Mã cv': 'JOB014',
    'Địa chỉ': '60 Đường Dương Nội, Hà Đông, Hà Nội',
    'Phường': 'Dương Nội',
    'Quận': 'Hà Đông',
    'Thành Phố': 'Hà Nội',
    'PIC': 'Lương Sơn Tùng',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'Tài khoản Portal': 'PORTAL014',
    'latitude': '20.9774',
    'longitude': '105.7380',
    'pic_id': 'USER003'
  },
  {
    'Week triển khai': 'W4',
    'Ngày chia': '05/04/2026',
    'Brand': 'Big C Thăng Long',
    'Mã cv': 'JOB015',
    'Địa chỉ': '222 Trần Duy Hưng, Cầu Giấy, Hà Nội',
    'Phường': 'Trung Hòa',
    'Quận': 'Cầu Giấy',
    'Thành Phố': 'Hà Nội',
    'PIC': 'Lương Sơn Tùng',
    'Status': 'Done',
    'Ngày hoàn thành': '07/04/2026',
    'Tài khoản Portal': 'PORTAL015',
    'latitude': '21.0093',
    'longitude': '105.7934',
    'pic_id': 'USER003'
  },
  // --- Nguyễn Lê Văn (USER004) ---
  {
    'Week triển khai': 'W2',
    'Ngày chia': '28/03/2026',
    'Brand': 'Lotte Mart Quận 7',
    'Mã cv': 'JOB003',
    'Địa chỉ': '469 Nguyễn Hữu Thọ, Tân Hưng, Quận 7, TP. HCM',
    'Phường': 'Tân Hưng',
    'Quận': 'Quận 7',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Lê Văn',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'Tài khoản Portal': 'PORTAL003',
    'latitude': '10.7366',
    'longitude': '106.7009',
    'pic_id': 'USER004'
  },
  {
    'Week triển khai': 'W2',
    'Ngày chia': '28/03/2026',
    'Brand': 'Big C An Lạc',
    'Mã cv': 'JOB004',
    'Địa chỉ': '1 Đường Số 3, An Lạc, Bình Tân, TP. HCM',
    'Phường': 'An Lạc',
    'Quận': 'Bình Tân',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Lê Văn',
    'Status': 'Done',
    'Ngày hoàn thành': '29/03/2026',
    'Tài khoản Portal': 'PORTAL004',
    'latitude': '10.7453',
    'longitude': '106.6040',
    'pic_id': 'USER004'
  },
  {
    'Week triển khai': 'W3',
    'Ngày chia': '01/04/2026',
    'Brand': 'Co.opmart Nguyễn Đình Chiểu',
    'Mã cv': 'JOB005',
    'Địa chỉ': '168 Nguyễn Đình Chiểu, Quận 3, TP. HCM',
    'Phường': 'Võ Thị Sáu',
    'Quận': 'Quận 3',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Lê Văn',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'Tài khoản Portal': 'PORTAL005',
    'latitude': '10.7788',
    'longitude': '106.6873',
    'pic_id': 'USER004'
  },
  // --- Nguyễn Hoàng Tuấn (USER005) — mirror of live sheet W15/W16 ---
  // W15 rows (QC4492 = Quận 12, QC3677/QC3679 = Quận 12 older but kept as reference)
  {
    'Week triển khai': 'W15',
    'Ngày chia': '09/04/2026',
    'Brand': 'Petrolimex - Cửa hàng',
    'Mã cv': 'QC4492',
    'Địa chỉ': '57/5 Bùi Công Trừng, khu phố 66, phường An Phú Đông, Q.12',
    'Quận': '12',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Hoàng Tuấn',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'latitude': '10.8670',
    'longitude': '106.6950',
    'pic_id': 'USER005'
  },
  {
    'Week triển khai': 'W15',
    'Ngày chia': '09/04/2026',
    'Brand': '30Shine',
    'Mã cv': 'QC3677',
    'Địa chỉ': '32 Nguyễn Ảnh Thủ, P. Hiệp Thành, Quận 12, TP Hồ Chí Minh',
    'Quận': '12',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Hoàng Tuấn',
    'Status': 'Done',
    'Ngày hoàn thành': '10/04/2026',
    'latitude': '10.8693',
    'longitude': '106.6472',
    'pic_id': 'USER005'
  },
  // W16 rows
  {
    'Week triển khai': 'W16',
    'Ngày chia': '16/04/2026',
    'Brand': 'Nguyễn Kim',
    'Mã cv': 'QC4877',
    'Địa chỉ': '312-314, Phan Văn Hớn, P.Tân Thới Nhất, Quận 12, TP.HCM',
    'Quận': '12',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Hoàng Tuấn',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'latitude': '10.8614',
    'longitude': '106.6589',
    'pic_id': 'USER005'
  },
  {
    'Week triển khai': 'W16',
    'Ngày chia': '16/04/2026',
    'Brand': 'Lotte Mart Gò Vấp',
    'Mã cv': 'JOB008',
    'Địa chỉ': '242 Nguyễn Văn Lượng, Phường 17, Gò Vấp, TP. HCM',
    'Quận': 'Gò Vấp',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Hoàng Tuấn',
    'Status': 'Done',
    'Ngày hoàn thành': '18/04/2026',
    'latitude': '10.8380',
    'longitude': '106.6688',
    'pic_id': 'USER005'
  },
  {
    'Week triển khai': 'W16',
    'Ngày chia': '16/04/2026',
    'Brand': 'Bình Tân Store',
    'Mã cv': 'QC4800',
    'Địa chỉ': '1 Đường Số 3, An Lạc, Bình Tân, TP. HCM',
    'Quận': 'Bình Tân',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Hoàng Tuấn',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'latitude': '10.7453',
    'longitude': '106.6040',
    'pic_id': 'USER005'
  },
  {
    'Week triển khai': 'W16',
    'Ngày chia': '16/04/2026',
    'Brand': 'Tân Bình Store',
    'Mã cv': 'QC4801',
    'Địa chỉ': '15 Cộng Hòa, Phường 4, Tân Bình, TP. HCM',
    'Quận': 'Tân Bình',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Hoàng Tuấn',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'latitude': '10.8010',
    'longitude': '106.6520',
    'pic_id': 'USER005'
  },
  {
    'Week triển khai': 'W16',
    'Ngày chia': '16/04/2026',
    'Brand': 'Tân Phú Store',
    'Mã cv': 'QC4802',
    'Địa chỉ': '30 Bờ Bao Tân Thắng, Sơn Kỳ, Tân Phú, TP. HCM',
    'Quận': 'Tân Phú',
    'Thành Phố': 'Hồ Chí Minh',
    'PIC': 'Nguyễn Hoàng Tuấn',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'latitude': '10.8016',
    'longitude': '106.6167',
    'pic_id': 'USER005'
  },
  // --- Trương Trọng Tân (USER006) ---
  {
    'Week triển khai': 'W1',
    'Ngày chia': '25/03/2026',
    'Brand': 'Big C Miền Đông',
    'Mã cv': 'JOB009',
    'Địa chỉ': '248 Bình Giã, Phường 10, Vũng Tàu',
    'Phường': 'Phường 10',
    'Quận': 'Vũng Tàu',
    'Thành Phố': 'Bà Rịa - Vũng Tàu',
    'PIC': 'Trương Trọng Tân',
    'Status': 'Done',
    'Ngày hoàn thành': '26/03/2026',
    'Tài khoản Portal': 'PORTAL009',
    'latitude': '10.3797',
    'longitude': '107.0842',
    'pic_id': 'USER006'
  },
  {
    'Week triển khai': 'W3',
    'Ngày chia': '01/04/2026',
    'Brand': 'Co.opmart Long Thành',
    'Mã cv': 'JOB010',
    'Địa chỉ': 'Quốc lộ 51, Long Thành, Đồng Nai',
    'Phường': 'Long Thành',
    'Quận': 'Long Thành',
    'Thành Phố': 'Đồng Nai',
    'PIC': 'Trương Trọng Tân',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'Tài khoản Portal': 'PORTAL010',
    'latitude': '10.7900',
    'longitude': '107.0200',
    'pic_id': 'USER006'
  },
  {
    'Week triển khai': 'W4',
    'Ngày chia': '05/04/2026',
    'Brand': 'Vincom Biên Hòa',
    'Mã cv': 'JOB011',
    'Địa chỉ': '1 Hà Huy Giáp, Quyết Thắng, Biên Hòa, Đồng Nai',
    'Phường': 'Quyết Thắng',
    'Quận': 'Biên Hòa',
    'Thành Phố': 'Đồng Nai',
    'PIC': 'Trương Trọng Tân',
    'Status': 'On-going',
    'Ngày hoàn thành': '',
    'Tài khoản Portal': 'PORTAL011',
    'latitude': '10.9574',
    'longitude': '106.8426',
    'pic_id': 'USER006'
  }
];
